export const GET_HOURLY_EVENTS = 'GET_HOURLY_EVENTS';
export const GET_HOURLY_STATS = 'GET_HOURLY_STATS';
export const FILTER_HOURLY_STATS = 'FILTER_HOURLY_STATS';
export const SHOW_EVENTS = 'SHOW_EVENTS';
export const SHOW_STATS = 'SHOW_STATS';
